apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.blogService.name }}
  labels: 
    {{- range $key, $value := .Values.inputs.blogService.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  type: {{ .Values.inputs.blogService.type }}
  selector:
    app: blog
  ports:
  - name: {{ .Values.inputs.blogService.ports.name }}
    port: {{ .Values.inputs.blogService.ports.port }}
    targetPort: {{ .Values.inputs.blogService.ports.targetPort }}