# Default values for blog-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

inputs:
  blogDeploy:
    name: blog-deploy
    replicaCount: 1
    image: 428411933129.dkr.ecr.us-east-1.amazonaws.com/blog:2.0
    limits:
      memory: 500M
      cpu: 1
    ports:
      containerPort: 5000
    environment:
      dbServer: stage-tech-aurora-postgres-db.cluster-cusgefost8jn.us-east-1.rds.amazonaws.com
      dbPort: 5432
      dbUsername: postgres
      dbName: postgres
      emailUsername: sujeetkumpadhi@gmail.com
      mailServer: smtp.gmail.com
      mailPort: 587
      mailUseTLS: "True"
      sqlalchemyTrack: "True"
      flaskApp: run.py
      bucket: app-s3-images
    secret:
      name: secretdata
      dbPassKey: dbpassword
      emailPassKey: emailpassword
      secretKey: secretkey
      aws_access_key_id: aws_access_key_id
      aws_secret_access_key: aws_secret_access_key
    hpa:
      name: blog-hpa
      minReplicas: 1
      maxReplicas: 2
      averageCPUUtilization: 80
      averageMemoryUtilization: 80
      pod_metric_name: http_request_per_second
      averageValue: 500m
  nginxDeploy:
    name: blog-nginx-deploy
    replicaCount: 1
    image: 428411933129.dkr.ecr.us-east-1.amazonaws.com/blog-nginx:1.0
    limits:
      memory: 128M
      cpu: 0.2
    ports:
      containerPort: 80
  nginxService:
    name: blog-endpoint
    type: ClusterIP
    ports:
      port: 80
      targetPort: 80
  blogService:
    name: web
    type: ClusterIP
    labels:
      svc: web-endpoint
    ports:
      port: 5000
      targetPort: 5000
      name: http
  clusterIssuer:
    name: letsencrypt-prod
    email: sujeetkupadhi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    secretName: letsencrypt-production-private-key
  ingress:
    name: ingress-service
    secretName: blog-simplifydev-co
    tlsHosts:
      - blog.simplifydev.co
    annotations:
      ingressClass: nginx                      
      sslRedirect: "True"        
    backends:
      - pathType: Prefix
        path: /
        serviceName: blog-endpoint
        servicePort: 80
  serviceMonitor:
    name: blog-app
    labels:
      app: blog-app
      release: kube-prometheus-stack
    endpoints:
      interval: 15s
      path: "/metrics"